name: Build Sameer Social APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Android project
        run: |
          unzip -q SameerSocial_Instagram_Design_Ready.zip -d android-project
      - name: Use latest index.html
        run: |
              cp index.html android-project/app/src/main/assets/index.html
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Build APK
        working-directory: android-project
        run: gradle --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SameerSocial-debug-apk
          path: android-project/app/build/outputs/apk/debug/app-debug.apk
